/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contest {
  'id' : string,
  'participants' : Array<Participant>,
  'totalSpots' : bigint,
  'matchId' : string,
  'entryFee' : bigint,
  'spotsFilled' : bigint,
  'prizePool' : bigint,
}
export interface FantasyTeam {
  'id' : string,
  'owner' : Principal,
  'matchId' : string,
  'players' : Array<Player>,
  'captain' : string,
  'totalCredits' : bigint,
  'viceCaptain' : string,
}
export interface Match {
  'id' : string,
  'status' : string,
  'team1' : string,
  'team2' : string,
  'venue' : string,
  'dateTime' : Time,
}
export interface Participant {
  'owner' : Principal,
  'rank' : [] | [bigint],
  'teamId' : string,
  'points' : bigint,
}
export interface Player {
  'id' : string,
  'credits' : bigint,
  'name' : string,
  'team' : string,
  'position' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : string,
  'transactionType' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContest' : ActorMethod<[Contest], undefined>,
  'addFunds' : ActorMethod<[bigint], string>,
  'addMatch' : ActorMethod<[Match], undefined>,
  'addPlayer' : ActorMethod<[Player], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createFantasyTeam' : ActorMethod<
    [string, Array<string>, string, string],
    string
  >,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContest' : ActorMethod<[string], Contest>,
  'getContestsForMatch' : ActorMethod<[string], Array<Contest>>,
  'getFantasyTeam' : ActorMethod<[string], [] | [FantasyTeam]>,
  'getMatch' : ActorMethod<[string], Match>,
  'getMyFantasyTeams' : ActorMethod<[], Array<FantasyTeam>>,
  'getPlayer' : ActorMethod<[string], [] | [Player]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'getWalletTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinContest' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];