/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Participant = IDL.Record({
  'owner' : IDL.Principal,
  'rank' : IDL.Opt(IDL.Nat),
  'teamId' : IDL.Text,
  'points' : IDL.Nat,
});
export const Contest = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(Participant),
  'totalSpots' : IDL.Nat,
  'matchId' : IDL.Text,
  'entryFee' : IDL.Nat,
  'spotsFilled' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const Time = IDL.Int;
export const Match = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'venue' : IDL.Text,
  'dateTime' : Time,
});
export const Player = IDL.Record({
  'id' : IDL.Text,
  'credits' : IDL.Nat,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'position' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const FantasyTeam = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'matchId' : IDL.Text,
  'players' : IDL.Vec(Player),
  'captain' : IDL.Text,
  'totalCredits' : IDL.Nat,
  'viceCaptain' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContest' : IDL.Func([Contest], [], []),
  'addFunds' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'addMatch' : IDL.Func([Match], [], []),
  'addPlayer' : IDL.Func([Player], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createFantasyTeam' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContest' : IDL.Func([IDL.Text], [Contest], ['query']),
  'getContestsForMatch' : IDL.Func([IDL.Text], [IDL.Vec(Contest)], ['query']),
  'getFantasyTeam' : IDL.Func([IDL.Text], [IDL.Opt(FantasyTeam)], ['query']),
  'getMatch' : IDL.Func([IDL.Text], [Match], ['query']),
  'getMyFantasyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
  'getPlayer' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getWalletTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinContest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Participant = IDL.Record({
    'owner' : IDL.Principal,
    'rank' : IDL.Opt(IDL.Nat),
    'teamId' : IDL.Text,
    'points' : IDL.Nat,
  });
  const Contest = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(Participant),
    'totalSpots' : IDL.Nat,
    'matchId' : IDL.Text,
    'entryFee' : IDL.Nat,
    'spotsFilled' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Match = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'venue' : IDL.Text,
    'dateTime' : Time,
  });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'credits' : IDL.Nat,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'position' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const FantasyTeam = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'matchId' : IDL.Text,
    'players' : IDL.Vec(Player),
    'captain' : IDL.Text,
    'totalCredits' : IDL.Nat,
    'viceCaptain' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContest' : IDL.Func([Contest], [], []),
    'addFunds' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'addMatch' : IDL.Func([Match], [], []),
    'addPlayer' : IDL.Func([Player], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createFantasyTeam' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContest' : IDL.Func([IDL.Text], [Contest], ['query']),
    'getContestsForMatch' : IDL.Func([IDL.Text], [IDL.Vec(Contest)], ['query']),
    'getFantasyTeam' : IDL.Func([IDL.Text], [IDL.Opt(FantasyTeam)], ['query']),
    'getMatch' : IDL.Func([IDL.Text], [Match], ['query']),
    'getMyFantasyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
    'getPlayer' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getWalletTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinContest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };